name:                annotated-exception
version:             0.3.0.2
github:              "parsonsmatt/annotated-exception"
license:             BSD3
author:              "Matt Parsons"
maintainer:          parsonsmatt@gmail.com
copyright:           "2018 Matt Parsons"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Exceptions, with checkpoints and context.
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/parsonsmatt/annotated-exception#readme>

dependencies:
- base >= 4.7 && < 5
- safe-exceptions
- containers
- text
- unliftio-core

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  annotated-exception-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - annotated-exception
    - hspec
    build-tools:
    - hspec-discover
